# config/packages/keyboardman_filemanager.yaml
keyboardman_filemanager:
  disks:
    default:
      label: Default
      storage: default.storage          # identifiant du storage Flysystem
      visibility: public
      signed_urls: true
      default_uri: "%env(resolve:DEFAULT_URI)%/media"