<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260124150000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create theme table for theme-generator.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE theme (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            name VARCHAR(255) NOT NULL,
            slug VARCHAR(255) DEFAULT NULL,
            generated_yaml_path VARCHAR(512) NOT NULL,
            generated_css_path VARCHAR(512) NOT NULL,
            PRIMARY KEY(id)
        )');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE theme');
    }
}
