<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260520120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Table builder_form_config (soumissions NodeForm)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE builder_form_config (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(64) NOT NULL, label VARCHAR(255) NOT NULL, recipient_emails JSON NOT NULL, email_subject_template TEXT NOT NULL, email_body_template TEXT NOT NULL, webhook_url VARCHAR(2000) DEFAULT NULL, enabled BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_builder_form_slug ON builder_form_config (slug)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE builder_form_config');
    }
}
