<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260716140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Table api_collection_definition pour déclarer des APIs NodeCollection depuis l’admin';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE api_collection_definition (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, api_id VARCHAR(64) NOT NULL, label VARCHAR(255) NOT NULL, type VARCHAR(16) NOT NULL, supported_modes JSON NOT NULL, endpoint_url VARCHAR(2000) NOT NULL, item_url_template VARCHAR(2000) DEFAULT NULL, query_params JSON NOT NULL, pagination_style VARCHAR(16) NOT NULL, member_path VARCHAR(128) NOT NULL, field_mapping JSON NOT NULL, headers JSON NOT NULL, enabled BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_api_collection_definition_api_id ON api_collection_definition (api_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE api_collection_definition');
    }
}
