<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260201120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create page table for page-crud (title, slug, theme_id, description, content).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE page (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            theme_id INT NOT NULL,
            title VARCHAR(255) NOT NULL,
            slug VARCHAR(255) NOT NULL,
            description TEXT DEFAULT NULL,
            content TEXT DEFAULT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_page_slug ON page (slug)');
        $this->addSql('ALTER TABLE page ADD CONSTRAINT FK_140AB62059027487 FOREIGN KEY (theme_id) REFERENCES theme (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_140AB62059027487 ON page (theme_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE page DROP CONSTRAINT FK_140AB62059027487');
        $this->addSql('DROP TABLE page');
    }
}
