<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260124140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create font and font_variant tables for theme-generator.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE font (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            name VARCHAR(255) NOT NULL,
            type VARCHAR(20) NOT NULL,
            fallback VARCHAR(255) NOT NULL,
            slug VARCHAR(255) NOT NULL,
            google_font_url VARCHAR(512) DEFAULT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3D2E2E8989D9B62D ON font (slug)');

        $this->addSql('CREATE TABLE font_variant (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            font_id INT NOT NULL,
            weight VARCHAR(50) NOT NULL,
            style VARCHAR(50) NOT NULL,
            width VARCHAR(50) NOT NULL,
            path VARCHAR(512) NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX IDX_CDE6F6F068931154 ON font_variant (font_id)');
        $this->addSql('ALTER TABLE font_variant ADD CONSTRAINT FK_CDE6F6F068931154 FOREIGN KEY (font_id) REFERENCES font (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE font_variant DROP CONSTRAINT FK_CDE6F6F068931154');
        $this->addSql('DROP TABLE font_variant');
        $this->addSql('DROP TABLE font');
    }
}
